version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run go env
      - run: go get -v ./...
      - run wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
      - run unzip https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
      - run mv terraform /usr/local/bin
      - run terraform
