version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      
      # Terraform
      - run: wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
      - run: unzip terraform_0.11.10_linux_amd64.zip
      - run: rm terraform_0.11.10_linux_amd64.zip
      - run: echo 'export PATH=$(pwd):$PATH' >> $BASH_ENV
      - run: terraform version

      # Go
      - run: go get -v ./...
      - run: go get github.com/tebeka/go2xunit

      # Execute tests
      - run: ./test.sh

      # Upload results
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./test-results
